name: Release

on:
  release:
    types:
      - published # reacts to releases and prereleases, but not their drafts

jobs:
  build-and-deploy-lib:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: "Setup Java 11"
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 11
    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@master
      with:
        cli: latest
    - name: clj tests
      run: ./scripts/kaocha
    - name: Build jar
      run: RELEASE=true clojure -T:build jar
    - name: Archive jar
      uses: actions/upload-artifact@v4
      with:
        name: contest.jar
        path: target/conjtest.jar
    - name: Deploy to Clojars
      run: clojure -X:deploy
      env:
        CLOJARS_USERNAME: ilmoraunio
        CLOJARS_PASSWORD: "${{ secrets.CLOJARS_DEPLOY_TOKEN }}"
